### ISSUE TITLE
Error occurs on .hide.keyboard() when type text in a field on iOS application. There is no possibility not to hide keyboard when it is needed by scenario.

### ISSUE THREAD

**Issue by NatalliaSamarava** [vividus-framework/vividus#1828]
**Describe the bug**
There is an error on .hideKeyboard() when user perform step "When I type `$text` in field located `$locator`". Step marked as broken and further steps are not running.
Some test scenarios are required not to hide keyboard and VIVIDUS does not provide any step now not to hide keyboard after finish typing a text. 
Scenario example:
Start type text in a Search bar -> Suggestions are shown
Once user submit search query suggestions are not present. 
Currently with VIVIDUS it is not possible to check this suggestion functionality

**To Reproduce**
Lifecycle:
Examples:
/tables/mobile/Search.table

Scenario:  Install and Open Application
Given I start mobile application with capabilities:
|name                          |value|
|appium:connectHardwareKeyboard|false |

Scenario: Verify Search Header
When I tap on element located `accessibilityId(search-tab)`
Then number of elements found by `accessibilityId(search-bar)` is equal to `1`
When I save `value` attribute value of element located `accessibilityId(search-bar-text-input)` to story variable `searchBarTextInput`
Then `${searchBarTextInput}` is equal to `<searchBarHint>`
When I type `<searchQuery>` in field located `accessibilityId(search-bar)`

**Expected behavior**
Text is typed in a field and keyboard is hidden without errors.

**Artifacts**
<img width="405" alt="Screenshot 2021-07-27 at 14 43 59" src="https://user-images.githubusercontent.com/11410482/127163728-4486d897-8fb6-4b8d-ae78-9a029596cab0.png">

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.6
 - OS: macOS Big Sur 11.4
 - Java: jdk-16.0.1

**Mobile Web (if applicable, please complete the following information):**
 - Emulator
 - Device: iPhone 12 Pro Max
 - OS: iOS 14.5

**Additional context**
org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'EPBYMINW1637', ip: 'fe80:0:0:0:c72:7f90:21a2:fdf9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.4', java.version: '16.0.1'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/Natallia_Samarava/Do..., browserName: , connectHardwareKeyboard: false, databaseEnabled: false, deviceName: iPhone 12 Pro Max, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: iOS, platformVersion: 14.5, snapshotMaxDepth: 100, takesScreenshot: true, udid: 62004BA4-B15A-4FB1-AED5-8C4..., webStorageEnabled: false}
Session ID: f94b92e1-814f-41c5-93d7-823febb84d8a
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:190)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:124)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:634)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.HidesKeyboard.hideKeyboard(HidesKeyboard.java:27)
	at org.vividus.mobileapp.action.KeyboardActions.performWithHideKeyboard(KeyboardActions.java:121)
	at org.vividus.mobileapp.action.KeyboardActions.typeText(KeyboardActions.java:72)
	at org.vividus.bdd.mobileapp.steps.TouchSteps.lambda$typeTextInField$1(TouchSteps.java:108)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.vividus.bdd.mobileapp.steps.TouchSteps.typeTextInField(TouchSteps.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:873)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.execute(StepCreator.java:700)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:685)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:387)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1335)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1214)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1193)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1205)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1273)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1103)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:997)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:964)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:299)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by valfirst** [comment]
The issues was fixed by #1832.
The feature request was extracted and moved to #1927
