### ISSUE TITLE
Add mechanism of http requests retrying

### ISSUE THREAD

**Issue by anastasi-n** [vividus-framework/vividus#214]
This will avoid unexpected issues during http requests occurring randomly from time to time for no apparent reason.
For example, for the following exception: "org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body"

**Suggestions:**
This mechanism can be configured by two properties:
- number of retries
- pattern of exception

**Comment by hannamor** [comment]
We also regularly face this issue:

"Truncated chunk (expected size: 8,192; actual size: 5,163)

org.apache.http.TruncatedChunkException: Truncated chunk (expected size: 8,192; actual size: 5,163)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:197)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:138)
	at org.vividus.http.client.HttpClient.execute(HttpClient.java:96)
	at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy36.execute(Unknown Source)
	at org.vividus.http.HttpRequestExecutor.execute(HttpRequestExecutor.java:118)
	at org.vividus.http.HttpRequestExecutor.executeHttpCallSafely(HttpRequestExecutor.java:101)
	at org.vividus.http.HttpRequestExecutor.lambda$executeHttpRequest$1(HttpRequestExecutor.java:88)
	at org.vividus.util.wait.Waiter.wait(Waiter.java:45)
	at org.vividus.http.HttpRequestExecutor.executeHttpRequest(HttpRequestExecutor.java:88)
	at org.vividus.http.HttpRequestExecutor.executeHttpRequest(HttpRequestExecutor.java:67)
	at org.vividus.bdd.steps.api.HttpRequestSteps.whenIDoHttpRequestToRelativeURL(HttpRequestSteps.java:153)
	at jdk.internal.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:834)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:399)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1280)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1151)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1130)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1142)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1177)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1065)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:952)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:920)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)"

**Comment by AliaksandraPaulenkova** [comment]
Please implement the following 3 properties to control HTTP requests retries:
1. HTTP methods to retry ( POST,GET...)
2. Status code to retry (500, 400..)
3. Number of retries (1,2..)
