### ISSUE TITLE
VIVIDUS expressions in properties

### ISSUE THREAD

**Issue by ikalinin1** [vividus-framework/vividus#2322]
Currently, it is not possible to use VIVIDUS expressions in global variables.

Steps to reproduce:
1. Add property:
```
bdd.variables.global.expr=#{anyOf(1,2)}
```
2. Use step in the story:
```
Then `1` is = `${expr}`
```

Actual behavior:
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method anyOf(java.lang.Integer,java.lang.Integer) on null context object
        at org.springframework.expression.spel.ast.MethodReference.throwIfNotNullSafe(MethodReference.java:154)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:105)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:95)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:141)
        at org.vividus.configuration.ConfigurationResolver.resolveSpelExpressions(ConfigurationResolver.java:260)
        ... 40 more
```

Expected behavior:
Expression resolved  in the step successfully

**Comment by ikalinin1** [comment]
We agreed to use a lazy resolution of expression(in the story), with limitation description in the docs
