### ISSUE TITLE
Browserstack: 'When I take screenshot' step gets broken for Phone/Tablet executions 

### ISSUE THREAD

**Issue by cherevachy** [vividus-framework/vividus#2442]
STR:
Execute test script that contains 'When I take screenshot' step on Phone/Tablet real devices through the BrowserStack cloud service.

Sample capabilities passed:
{
  "appiumVersion" : "1.21.0",
  "browserName" : "Chrome",
  "bstack:options" : {
    "os" : "Android",
    "osVersion" : "10.0",
    "realMobile" : "true",
    "idleTimeout" : "360",
    "appiumVersion" : "1.21.0",
    "sessionName" : "UI_Homepage",
    "deviceName" : "Samsung Galaxy S20",
    "resolution" : "",
    "local" : "false"
  },
  "deviceOrientation" : "portrait",
  "goog:chromeOptions" : {
    "args" : [ ],
    "extensions" : [ ]
  },
  "platform" : "ANDROID",
  "platform-version" : "10.0",
  "platformName" : "Android"
}

Session capabilities:
{
  "appium:systemPort" : 8202,
  "appium:skipServerInstallation" : true,
  "appium:newCommandTimeout" : 0,
  "appium:takesScreenshot" : true,
  "appium:warnings" : { },
  "appium:desired" : {
    "goog:chromeOptions" : {
      "args" : [ "--proxy-bypass-list=<-loopback>", "test-type", "--proxy-server=http://194.165.185.31:26082", "--disable-features=Translate" ]
    },
    "platformName" : "Android",
    "browserName" : "chrome",
    "newCommandTimeout" : 0,
    "deviceName" : "android",
    "chromedriverPorts" : [ [ 18122, 18132 ] ],
    "systemPort" : 8202,
    "appiumVersion" : "1.21.0",
    "deviceOrientation" : "portrait",
    "platform" : "android",
    "platform-version" : "10.0",
    "skipServerInstallation" : true
  },
  "appium:deviceApiLevel" : 29,
  "appium:locationContextEnabled" : false,
  "appium:deviceScreenSize" : "1080x2400",
  "appium:deviceManufacturer" : "samsung",
  "appium:pixelRatio" : 3,
  "goog:chromeOptions" : {
    "args" : [ "--proxy-bypass-list=<-loopback>", "test-type", "--proxy-server=http://194.165.185.31:26082", "--disable-features=Translate" ]
  },
  "appium:platform-version" : "10.0",
  "appium:deviceOrientation" : "portrait",
  "browserName" : "chrome",
  "platformName" : "Android",
  "appium:networkConnectionEnabled" : true,
  "appium:deviceScreenDensity" : 480,
  "appium:viewportRect" : {
    "left" : 0,
    "top" : 77,
    "width" : 1080,
    "height" : 2101
  },
  "appium:appiumVersion" : "1.21.0",
  "appium:deviceModel" : "SM-G981B",
  "appium:platformVersion" : "10",
  "appium:databaseEnabled" : false,
  "appium:deviceUDID" : "RFCN1048XJH",
  "appium:statBarHeight" : 77,
  "appium:webStorageEnabled" : false,
  "appium:appActivity" : "com.google.android.apps.chrome.Main",
  "appium:chromedriverPorts" : [ [ 18122, 18132 ] ],
  "appium:deviceName" : "RFCN1048XJH",
  "appium:javascriptEnabled" : true,
  "appium:appPackage" : "com.android.chrome"
}

Actual:
java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.getSize(RemoteWebDriver.java:939)
	at org.vividus.selenium.manager.GenericWebDriverManager.getSize(GenericWebDriverManager.java:77)
	at org.vividus.selenium.manager.GenericWebDriverManager.runInNativeContext(GenericWebDriverManager.java:91)
	at org.vividus.selenium.manager.GenericWebDriverManager.getSize(GenericWebDriverManager.java:60)
	at org.vividus.selenium.screenshot.ScreenshotFileNameGenerator.generateScreenshotFileName(ScreenshotFileNameGenerator.java:42)
	at org.vividus.selenium.screenshot.AbstractScreenshotTaker.generateScreenshotFileName(AbstractScreenshotTaker.java:114)
	at org.vividus.selenium.screenshot.WebScreenshotTaker.takeScreenshot(WebScreenshotTaker.java:68)
	at org.vividus.selenium.screenshot.WebScreenshotTaker.takeScreenshot(WebScreenshotTaker.java:55)
	at org.vividus.steps.ui.ScreenshotTakingSteps.takeScreenshot(ScreenshotTakingSteps.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:857)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:678)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:390)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1385)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1233)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1214)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1225)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1273)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1160)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:1049)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:1024)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:474)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:441)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:300)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:273)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by cherevachy** [comment]
The issue is no longer reproducible
