### ISSUE TITLE
Scenarios are not run locally using IE browser

### ISSUE THREAD

**Issue by veranikaChyrun** [vividus-framework/vividus#327]
**Description:**
When trying to use IEDriverServer.exe to run tests locally using configuration
configuration.profile=web/desktop/iexplore 
browser is opened but test fails with exception

**To Reproduce**
1. Configure configuration.profile property as web/desktop/iexplore
2. Start the test

**Expected behavior**
Tests are run using IEDriverServer.exe

**Actual Result** 
Test is failed

**Artifacts**
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:27136
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'EPBYMINW0994', ip: '10.6.190.44', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.2'
Driver info: driver.version: EventFiringWebDriver
org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:27136
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'EPBYMINW0994', ip: '10.6.190.44', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.2'
Driver info: driver.version: EventFiringWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:512)
	at org.vividus.selenium.driver.DelegatingWebDriver.executeScript(DelegatingWebDriver.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:106)
	at com.sun.proxy.$Proxy53.executeScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:230)
	at org.vividus.ui.web.action.JavascriptActions.executeScript(JavascriptActions.java:62)
	at org.vividus.ui.web.action.NavigateActions.handleTimeoutException(NavigateActions.java:119)
	at org.vividus.ui.web.action.NavigateActions.navigateTo(NavigateActions.java:51)
	at org.vividus.ui.web.action.NavigateActions.loadPage(NavigateActions.java:106)
	at org.vividus.bdd.steps.ui.web.PageSteps.iAmOnPage(PageSteps.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:834)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1280)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1151)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1130)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1142)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1212)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1060)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:952)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:920)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:27136
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:162)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:57)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 37 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:579)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 58 more

**Execution environment (please complete the following information):**
 - Vividus version: 
 - OS: Windows 10
 - Java: JDK13

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 
![image](https://user-images.githubusercontent.com/60783053/74722577-36e11680-524a-11ea-8b3d-98654efcdbde.png)

TRIED TO USE ADDITIONAL CONFIGS
system.wdm.architecture=32
system.webdriver.ie.driver=C:/Path/to/driver/IEDriverServer.exe
selenium.timeout.page-load-timeout=5
The same result

**Comment by valfirst** [comment]
The issue was solved by setting all zones (Internet, Local intranet, Trusted sites, Restricted sites) to the same protected mode.
https://stackoverflow.com/a/14957443/2067574
