### ISSUE TITLE
Implement JBehave-JUnit-Runner for Vividus

### ISSUE THREAD

**Issue by valfirst** [vividus-framework/vividus#438]
Current `jbehave-junit-runner` is strongly relies on jbehave-core and can't take into account Vividus features like batches, per-batch configuration of meta-filters and etc.

Possible solutions:
- fork and extend `jbehave-junit-runner`
- implement own runner

**Comment by dKatechev** [comment]
Scenarios with Examples table are not running properly with Eclipse JUnit 4 test runner.
Test execution is failing with the exception below:

`2020-04-21 12:30:53,481 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - Failed to run story file:/D:/crepo/commerce-api/v-seph/instagram-tests/bin/main/story/seph/instagram/management/CE-301 Management Service - Accept Order Record.story
2020-04-21 12:30:53,482 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - java.lang.NullPointerException
2020-04-21 12:30:53,483 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at com.github.valfirst.jbehave.junit.monitoring.JUnitScenarioReporter$TestState.getNextOrNull(JUnitScenarioReporter.java:408)
2020-04-21 12:30:53,483 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at com.github.valfirst.jbehave.junit.monitoring.JUnitScenarioReporter$TestState.moveToNextExample(JUnitScenarioReporter.java:392)
2020-04-21 12:30:53,483 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at com.github.valfirst.jbehave.junit.monitoring.JUnitScenarioReporter$TestState.access$1300(JUnitScenarioReporter.java:368)
2020-04-21 12:30:53,483 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at com.github.valfirst.jbehave.junit.monitoring.JUnitScenarioReporter.example(JUnitScenarioReporter.java:234)
2020-04-21 12:30:53,483 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.reporters.DelegatingStoryReporter.example(DelegatingStoryReporter.java:143)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.reporters.ConcurrentStoryReporter.example(ConcurrentStoryReporter.java:324)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.reporters.DelegatingStoryReporter.example(DelegatingStoryReporter.java:143)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1246)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1095)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:987)
2020-04-21 12:30:53,484 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:955)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-04-21 12:30:53,485 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingEmbedderMonitor - at java.base/java.lang.Thread.run(Thread.java:834)`

However, gradle task runStories is running successfully.
