### ISSUE TITLE
Scenario fails with ArrayIndexOutOfBoundsException when data table contains "," and merging transformer used 

### ISSUE THREAD

**Issue by remiprink** [vividus-framework/vividus#610]
**Describe the bug**
Scenario fails with the following exception in case commas are used in the data table under MERGING transformer: 
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.jbehave.core.model.ExamplesTable$TableProperties.parseProperties(ExamplesTable.java:522)
	at org.jbehave.core.model.ExamplesTable$TableProperties.<init>(ExamplesTable.java:513)
	at org.jbehave.core.model.TableParsers.parseProperties(TableParsers.java:39)
	at org.jbehave.core.model.TableParsers.parseProperties(TableParsers.java:26)
	at org.jbehave.core.model.ExamplesTableFactory.getPropertiesData(ExamplesTableFactory.java:97)
	at org.jbehave.core.model.ExamplesTableFactory.createExamplesTable(ExamplesTableFactory.java:75)
	at org.jbehave.core.steps.ParameterConverters$FunctionalParameterConverter.convertValue(ParameterConverters.java:599)
	at org.jbehave.core.steps.ParameterConverters$FunctionalParameterConverter.convertValue(ParameterConverters.java:584)
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340)
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349)
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72)
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439)
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:399)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1305)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1188)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1167)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1179)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1244)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1095)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:987)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:955)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
Use the following as an example:
Step that fails: 
```
When I generate parquet with the name `<path>` using schema `<schemasPath>/2020-04-21.json` and data:
`|id |user_comment               |
 |3  |Some data, comma separated |`
```
Composite step used:
```
Composite: When I generate parquet with the name `$fileName` using schema `$schema` and data:
`$table`
Priority: 1
Given I initialize the scenario variable `scalaScript` using template `templates/generate_parquet.ftl` with parameters:
{transformer=MERGING, mergeMode=columns, fillerValue= , tables=<table>}
|_schema |_file                                                 |
|<schema>|<fileName>_#{generateDate(P, YYYY-MM-dd'T'hh-mm-ss)}  |
```

**Expected behavior**
Vividus throws an error, that invalid characters used in the data table, not unhandled exception

**Execution environment (please complete the following information):**
 - Vividus version: 0.2.3-SNAPSHOT
 - OS: Win 10
 - Java: Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)

**Comment by remiprink** [comment]
priority - p5

**Comment by abudevich** [comment]
Exception encountered because of using not escaped commas in table parameter `$table`. As decision you can add expression, which will be do this: escape commas in used table.

**_Example:_**
```
Composite: When I generate parquet with the name `$fileName` using schema `$schema` and data:
`$table`
Priority: 1
Given I initialize the scenario variable `scalaScript` using template `templates/generate_parquet.ftl` with parameters:
{transformer=MERGING, mergeMode=columns, fillerValue= , tables=#{replaceAllByRegExp((,), \\$1, <table>)}}
|_schema |_file                                                 |
|<schema>|<fileName>_#{generateDate(P, YYYY-MM-dd'T'hh-mm-ss)}  |
```

**Comment by valfirst** [comment]
**Summary**
The root cause of the issue is commas in the table data. The presence of non-escaped commas leads to inability to parse the transformer properties (which are separated by comma) properly. And finally the parsing logic throws the exception.

**Solution**
Since it's not possible to determine whether comma is a part of data or separator of table properties, users must escape commas in the data: 
```
\,
```
If the data is dynamic, the solution provided above can be applied: 
```
#{replaceAllByRegExp((,), \\$1, <table>)}
```
