### ISSUE TITLE
[composite file] truncate space in user action "When I wait `$duration` with `$pollingDuration` polling until element located `$locator` becomes $state"

### ISSUE THREAD

**Issue by AlenaSikorskaya** [vividus-framework/vividus#648]
I added user action "When I wait `$duration` with `$pollingDuration` polling until element located `$locator` becomes $state" to composite file
and left a space at the end of the step. As a result the step was skipped
![image](https://user-images.githubusercontent.com/58731281/83661163-6a179d80-a5ce-11ea-83d1-676952e7fa2b.png)

![image](https://user-images.githubusercontent.com/58731281/83661107-5a985480-a5ce-11ea-9acf-fad4d7dacc27.png)

2020-06-03 18:55:19,267 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingStoryReporter - When I wait `PT30S` with `PT1S` polling until element located `By.xpath(.//div[contains(text(),'Task has been created')])` becomes VISIBLE  (FAILED)
(org.jbehave.core.steps.ParameterConverters$ParameterConvertionFailed: Failed to convert VISIBLE_ for Enum org.vividus.ui.web.State)
2020-06-03 18:55:19,267 [batch-1-thread-1] ERROR org.vividus.bdd.log.LoggingStoryReporter - Step is failed with exception
org.jbehave.core.failures.UUIDExceptionWrapper: When I wait `PT30S` with `PT1S` polling until element located `By.xpath(.//div[contains(text(),'Task has been created')])` becomes VISIBLE 
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:856) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:399) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1305) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1188) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1167) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1179) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1244) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1095) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:987) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:955) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266) [jbehave-core-4.6.4-alpha.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: org.jbehave.core.steps.ParameterConverters$ParameterConvertionFailed: Failed to convert VISIBLE_ for Enum org.vividus.ui.web.State
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:958) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:956) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.vividus.ui.web.State.VISIBLE_
	at java.lang.Enum.valueOf(Enum.java:266) ~[?:?]
	at org.vividus.ui.web.State.valueOf(State.java:25) ~[vividus-plugin-web-app-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:956) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more2020-06-03 18:55:19,267 [batch-1-thread-1] INFO  org.vividus.bdd.log.LoggingStoryReporter - When I wait `PT30S` with `PT1S` polling until element located `By.xpath(.//div[contains(text(),'Task has been created')])` becomes VISIBLE  (FAILED)
(org.jbehave.core.steps.ParameterConverters$ParameterConvertionFailed: Failed to convert VISIBLE_ for Enum org.vividus.ui.web.State)
2020-06-03 18:55:19,267 [batch-1-thread-1] ERROR org.vividus.bdd.log.LoggingStoryReporter - Step is failed with exception
org.jbehave.core.failures.UUIDExceptionWrapper: When I wait `PT30S` with `PT1S` polling until element located `By.xpath(.//div[contains(text(),'Task has been created')])` becomes VISIBLE 
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:856) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:399) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1305) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1188) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1167) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1179) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1244) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1095) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:987) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:955) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293) [jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266) [jbehave-core-4.6.4-alpha.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: org.jbehave.core.steps.ParameterConverters$ParameterConvertionFailed: Failed to convert VISIBLE_ for Enum org.vividus.ui.web.State
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:958) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:956) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.vividus.ui.web.State.VISIBLE_
	at java.lang.Enum.valueOf(Enum.java:266) ~[?:?]
	at org.vividus.ui.web.State.valueOf(State.java:25) ~[vividus-plugin-web-app-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.jbehave.core.steps.ParameterConverters$EnumConverter.convertValue(ParameterConverters.java:956) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:989) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters$FluentEnumConverter.convertValue(ParameterConverters.java:985) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:72) ~[vividus-bdd-engine-0.2.4-SNAPSHOT.jar:0.2.4-SNAPSHOT]
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830) ~[jbehave-core-4.6.4-alpha.3.jar:?]
	... 18 more

**Comment by AlenaSikorskaya** [comment]
p4

**Comment by AlenaSikorskaya** [comment]
1.4.0-SNAPSHOT
