### ISSUE TITLE
Unable to load https page when Proxy is ON

### ISSUE THREAD

**Issue by ananyevN** [vividus-framework/vividus#759]
When we turn on the proxy and try to load https page we face an error: ERR_TUNNEL_CONNECTION_FAILED

Steps to reproduce:

1) Create story:
Meta:
    @proxy
Scenario: B2 event
Given I am on the main application page

2) Properties:
proxy.enabled=true
proxy.trust-all-servers=true
web-application.main-page-url=**https**://example.com

---------------------------------------------------------------------------------------------------------------------
Expected: The page is load
Actual: The page doesn't load. There is an error ERR_TUNNEL_CONNECTION_FAILED
![errorpng](https://user-images.githubusercontent.com/58809891/88067231-67b9d480-cb77-11ea-8166-084c8458ac5f.png)

**Comment by ananyevN** [comment]
https://github.com/vividus-framework/vividus/pull/764

**Comment by ananyevN** [comment]
Standalone littleproxy uses netty4.1.34, but required 4.1.44
![Untitled](https://user-images.githubusercontent.com/58809891/88266816-85eb1600-ccd8-11ea-8a80-209190bc4eb8.png)


LOG
------------------------------------------------------------
2020-07-23 11:30:41,897 [LittleProxy-0-ProxyToServerWorker-2] ERROR org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0xf152b210, L:/100.64.8.134:63290 - R:www.gstatic.com/216.58.207.67:443]: Caught an exception on ProxyToServerConnection
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.maxFastWritableBytes()I
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:86) ~[netty-codec-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:269) ~[netty-codec-4.1.44.Final.jar:4.1.44.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-all-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [netty-all-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-all-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-all-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.1.34.Final.jar:4.1.34.Final]
