### ISSUE TITLE
It is impossible to run stories if one story is set to be skipped where main page url is missing in properties

### ISSUE THREAD

**Issue by AlenaSikorskaya** [vividus-framework/vividus#784]
**To Reproduce**
Scenario: browsers, platforms
Meta:
@skip
@layout desktop chrome_phone phone
When I go to the relative URL '${authority}<rel-url>'
When I ${visual-action} baseline with `${brand}#{eval(`<rel-url>`.replaceAll(`/`,`-`))}-${profile}`
Examples:
{transformer=FROM_SITEMAP, siteMapRelativeUrl=/sitemap.xml, ignoreErrors=true, column=rel-url}
{transformer=FILTERING, byMaxRows=5}

**Actual**
java.lang.NullPointerException
	at org.vividus.util.UriUtils.buildNewUrl(UriUtils.java:235)
	at org.vividus.util.UriUtils.buildNewRelativeUrl(UriUtils.java:277)
	at org.vividus.sitemap.SiteMapParser.buildSiteMapUrl(SiteMapParser.java:121)
	at org.vividus.sitemap.SiteMapParser.parse(SiteMapParser.java:107)
	at org.vividus.transformer.SiteMapTableTransformer.lambda$fetchUrls$1(SiteMapTableTransformer.java:61)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.vividus.transformer.SiteMapTableTransformer.fetchUrls(SiteMapTableTransformer.java:56)
	at org.vividus.transformer.AbstractFetchingUrlsTableTransformer.transform(AbstractFetchingUrlsTableTransformer.java:50)
	at org.jbehave.core.model.TableTransformers.transform(TableTransformers.java:45)
	at org.jbehave.core.model.ExamplesTable.applyTransformers(ExamplesTable.java:229)
	at org.jbehave.core.model.ExamplesTable.<init>(ExamplesTable.java:207)
	at org.jbehave.core.model.ExamplesTableFactory.createExamplesTable(ExamplesTableFactory.java:86)
	at org.jbehave.core.parsers.RegexStoryParser.parseExamplesTable(RegexStoryParser.java:352)
	at org.jbehave.core.parsers.RegexStoryParser.parseScenario(RegexStoryParser.java:313)
	at org.jbehave.core.parsers.RegexStoryParser.parseScenariosFrom(RegexStoryParser.java:290)
	at org.jbehave.core.parsers.RegexStoryParser.parseStory(RegexStoryParser.java:89)
	at org.jbehave.core.embedder.PerformableTree.storyOfPath(PerformableTree.java:331)
	at org.jbehave.core.embedder.StoryManager.storyOfPath(StoryManager.java:61)
	at org.jbehave.core.embedder.StoryManager.storiesOfPaths(StoryManager.java:67)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.createPerformableTree(JUnitReportingRunner.java:136)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.buildDescriptionFromStories(JUnitReportingRunner.java:122)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.<init>(JUnitReportingRunner.java:42)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by AlenaSikorskaya** [comment]
p4
