### ISSUE TITLE
transformer=FILTERING + transformer=FROM_EXCEL fails with specific data in Excel

### ISSUE THREAD

**Issue by AlenaSikorskaya** [vividus-framework/vividus#951]
Vividus fails on row 81 from Excel doc
Please use
key-actions.story
key-actions-one-click_81-row-only.table
Excel.xlsx

allure reports are attached

Actual:
![image](https://user-images.githubusercontent.com/58731281/93335432-20765a00-f82f-11ea-9ce0-98babc1d5457.png)

I added error to comment

Expected:
![image](https://user-images.githubusercontent.com/58731281/93335539-469bfa00-f82f-11ea-919c-194ff6958f0a.png)

**Comment by AlenaSikorskaya** [comment]
p2

**Comment by AlenaSikorskaya** [comment]
java.lang.IllegalArgumentException: Invalid locator format. Expected matches [(?:By\.)?([a-zA-Z]+)\((.+?)\):?([a-zA-Z]*)?] Actual: [By.cssSelector()]
	at org.vividus.ui.web.util.SearchAttributesConversionUtils.convertToSearchAttributes(SearchAttributesConversionUtils.java:80)
	at org.vividus.bdd.converter.StringToSearchAttributesConverter.convertValue(StringToSearchAttributesConverter.java:33)
	at org.vividus.bdd.converter.StringToSearchAttributesConverter.convertValue(StringToSearchAttributesConverter.java:27)
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340)
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349)
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:77)
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439)
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1309)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1192)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1171)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1183)
	at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1248)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1083)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:975)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:943)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by valfirst** [comment]
> java.lang.IllegalArgumentException: Invalid locator format. Expected matches [(?:By.)?([a-zA-Z]+)((.+?)):?([a-zA-Z]*)?] Actual: [By.cssSelector()]
at org.vividus.ui.web.util.SearchAttributesConversionUtils.convertToSearchAttributes(SearchAttributesConversionUtils.java:80)
at org.vividus.bdd.converter.StringToSearchAttributesConverter.convertValue(StringToSearchAttributesConverter.java:33)
at org.vividus.bdd.converter.StringToSearchAttributesConverter.convertValue(StringToSearchAttributesConverter.java:27)
at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:340)
at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:349)
at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:77)
at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:439)
at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:49)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:889)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:830)
at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:392)
at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1309)
at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1192)
at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1171)
at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1183)
at org.jbehave.core.embedder.PerformableTree$ExamplePerformableScenario.perform(PerformableTree.java:1248)
at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1083)
at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:975)
at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:943)
at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:293)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)

I'm not sure that this error correlates with the original issue
